#!/bin/env python3
"""Convert per-icon pixel-art PNGs into packed 4-bit (P4) palette-indexed blobs.

The P4 framebuffer can't use the firmware ``sprite()`` path, so icons are stored
as 4-bit indices into the shared 16-colour palette and drawn by a tiny custom
blitter.  Because the icons are flat pixel-art (no anti-aliasing) authored in
EXACTLY the palette colours, every pixel maps to a palette slot with no loss.

Usage:
    python icons-to-p4.py --in src/assets --out src/pico/displays/shared/_icons_data.py

Output: a generated Python module of named ``(w, h, blob)`` tuples, ready to
import on-device.  Packing: row-major nibble stream, high nibble = left pixel;
slot 0 (BLACK) is the transparent index (skipped by the blitter).
"""

import argparse
import pathlib
import sys
import types

from PIL import Image

# Import the canonical 16-colour palette so the converter and the device can
# never drift.  ``displays.palette`` keeps its module-level imports to
# ``micropython.const`` only, so a tiny shim is all CPython needs.
_TOOL_DIR = pathlib.Path(__file__).resolve().parent
_PICO_DIR = _TOOL_DIR.parent / "pico"
if str(_PICO_DIR) not in sys.path:
    sys.path.insert(0, str(_PICO_DIR))
if "micropython" not in sys.modules:
    _mp = types.ModuleType("micropython")
    _mp.const = lambda x: x  # type: ignore[attr-defined]
    sys.modules["micropython"] = _mp

from displays.palette import ICON_SLOTS, PALETTE_RGB  # noqa: E402

# Exact-match map limited to the slots icons may use (ICON_SLOTS excludes the
# spare slots 12-15) so a stray/off-palette colour errors out instead of
# silently snapping to a spare.
_EXACT = {PALETTE_RGB[i]: i for i in ICON_SLOTS}


def _index_of(rgb, name, x, y):
    if rgb in _EXACT:
        return _EXACT[rgb]
    raise SystemExit(
        "ERROR: {} pixel ({},{}) colour {} is not a palette colour.\n"
        "       Author icons with the exact palette RGBs.".format(name, x, y, rgb))


def _pack(img, name):
    """img: an RGB(A) PIL image already cropped to one icon.  Returns packed bytes."""
    w, h = img.size
    px = img.convert("RGB").load()
    out = bytearray((w * h + 1) // 2)
    ni = 0
    for row in range(h):
        for col in range(w):
            idx = _index_of(px[col, row], name, col, row)
            if ni & 1:
                out[ni >> 1] |= idx
            else:
                out[ni >> 1] = idx << 4
            ni += 1
    return bytes(out), w, h


def _emit(entries, out_path):
    """entries: list of (name, packed_bytes, w, h).

    Emits each icon as a self-describing ``NAME = (w, h, blob)`` tuple so the
    blitter needs no separate dimensions table.
    """
    lines = [
        '"""GENERATED by src/tools/icons-to-p4.py -- DO NOT EDIT.',
        "",
        "Packed 4-bit palette-indexed icon blobs as ``(width, height, data)``;",
        "data is a row-major nibble stream, high nibble = left pixel.  Slot 0 =",
        "transparent.  Drawn by the P4 blitter.",
        '"""',
        "",
    ]
    total = 0
    for name, blob, w, h in entries:
        total += len(blob)
        lines.append("{} = ({}, {}, {!r})".format(name, w, h, blob))
    lines.append("")
    pathlib.Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="indir", required=True, help="directory of per-icon PNGs")
    ap.add_argument("--out", required=True, help="output .py module path")
    args = ap.parse_args()

    entries = []
    for png in sorted(pathlib.Path(args.indir).glob("*.png")):
        name = png.stem.upper()
        blob, w, h = _pack(Image.open(png), name)
        entries.append((name, blob, w, h))

    total = _emit(entries, args.out)
    print("Wrote {} ({} icons, {} bytes packed) -> {}".format(
        pathlib.Path(args.out).name, len(entries), total, args.out))


if __name__ == "__main__":
    main()
